modLoader="javafml"
loaderVersion="[35,)"
license="Direct License"

[[mods]]
modId="jiomes"
version="1.0.5.2"
displayName="Jiomes"
credits="The entire mod is being made by Jaden/Red."
displayURL="http://iredmc.us.to/jadensmods/"
authors="Red (misterrredstone/Jaden LeMieux/iRedMC)"
description='''
This is my test mod that I will just be using to test various thngs so yea. -jaden-
'''

[[dependencies.jiomes]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.4]"
    ordering="NONE"
    side="BOTH"




